// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQKWKNnyUeKUz1KH_4vf---M31FaLbRuk',
    appId: '1:1094221740655:web:affffd90a8bb6a867f6b9a',
    messagingSenderId: '1094221740655',
    projectId: 'examen-5c422',
    authDomain: 'examen-5c422.firebaseapp.com',
    storageBucket: 'examen-5c422.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCODysRTp7-vWKccWfv_sBXHTaxAwEcsog',
    appId: '1:1094221740655:android:d5ceb58d4fc0e6aa7f6b9a',
    messagingSenderId: '1094221740655',
    projectId: 'examen-5c422',
    storageBucket: 'examen-5c422.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABgfzthTxvNu-pno9sG3YzWd10a99q9QQ',
    appId: '1:1094221740655:ios:da3c7723af419bcb7f6b9a',
    messagingSenderId: '1094221740655',
    projectId: 'examen-5c422',
    storageBucket: 'examen-5c422.appspot.com',
    iosBundleId: 'com.example.smartphoneApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABgfzthTxvNu-pno9sG3YzWd10a99q9QQ',
    appId: '1:1094221740655:ios:da3c7723af419bcb7f6b9a',
    messagingSenderId: '1094221740655',
    projectId: 'examen-5c422',
    storageBucket: 'examen-5c422.appspot.com',
    iosBundleId: 'com.example.smartphoneApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQKWKNnyUeKUz1KH_4vf---M31FaLbRuk',
    appId: '1:1094221740655:web:5782426d72bc67437f6b9a',
    messagingSenderId: '1094221740655',
    projectId: 'examen-5c422',
    authDomain: 'examen-5c422.firebaseapp.com',
    storageBucket: 'examen-5c422.appspot.com',
  );
}
